spring.datasource.url=jdbc:postgresql://postgres-user:5432/user_db
spring.datasource.username=user_admin
spring.datasource.password=user_pass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.application.name=userservice
