spring.datasource.url=jdbc:postgresql://localhost:5436/user_db
spring.datasource.username=user_admin
spring.datasource.password=user_pass

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.jpa.open-in-view=false

spring.flyway.enabled=true
logging.level.org.flywaydb=DEBUG

spring.application.name=userservice
